Q1.


In [76]:
import numpy as np
array_1d=np.array([0,1,2,3,4,5,6,7,8,9])
print(array_1d)
print("====================================")
array=np.arange(10)
print(array)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


Q2.

In [77]:
import numpy as np
array_2d=np.arange(1,10).reshape(3,3)
print(array_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Q3.

In [78]:
import numpy as np
array=np.eye(3)
print(array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Q4.

In [79]:
import numpy as np
random_number=np.random.rand(10)
print(random_number)

[0.78154578 0.25357595 0.76016705 0.82919958 0.70661992 0.04321611
 0.97970433 0.50102359 0.39767654 0.07257668]


Q5.

In [80]:
import numpy as np
a=np.zeros(10)
print(a)
b=np.ones(10)
print(b)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


Q6.

In [81]:
import numpy as np
a=np.array([10,20,30,40,50])
b=a[2]
print(b)

30


Q7.

In [82]:
import numpy as np
matrix=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
b=matrix[1,2]
print(b)

7


Q8.

In [83]:
import numpy as np
a=np.array([5,10,15,20,25])
print(a[-1])

25


Q9.

In [84]:
import numpy as np
a=np.array([1,3,5,7,9,11])
print(a[1],a[3],a[4])
print("=================================")
selected_elements=a[[1,3,4]]
print(selected_elements)

3 7 9
[3 7 9]


Q10.

In [85]:
import numpy as np
array_3d=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(array_3d.shape)
print(array_3d[1,1,1])


(2, 2, 2)
8


Q11.

In [86]:
import numpy as np
a=np.array([2,4,6,8,10,12])
print(a[0:3:1])
print("=======================")
print(a[:3])

[2 4 6]
[2 4 6]


Q12.

In [87]:
import numpy as np
matrix=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
sub_array=matrix[:2,2:]
print(sub_array)
print("========================")
sub_array=matrix[:2,-2:]
print(sub_array)

[[3 4]
 [7 8]]
[[3 4]
 [7 8]]


Q13.

In [88]:
import numpy as np
a=np.array([0,1,2,3,4,5,6,7,8,9])
print(a[0:9:2])
print("=============================")
print(a[::2])

[0 2 4 6 8]
[0 2 4 6 8]


Q14.

In [89]:
import numpy as np
matrix=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(matrix[0:3,2:])
print("===============================")
print(matrix[:,-2:])

[[ 3  4]
 [ 7  8]
 [11 12]]
[[ 3  4]
 [ 7  8]
 [11 12]]


Q15.

In [90]:
import numpy as np
matrix=np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])
print(matrix[1:4,1:4])

[[2 3 4]
 [2 3 4]
 [2 3 4]]


Q16.

In [91]:
import numpy as np
int_array=np.arange(6)
float_array=int_array.astype(float)
print(float_array)

[0. 1. 2. 3. 4. 5.]


Q17.

In [92]:
import numpy as np
bool_array=np.array([[True,False,True],[False,True,False],[True,True,False]])
print(bool_array)

[[ True False  True]
 [False  True False]
 [ True  True False]]


Q18.

In [93]:
import numpy as np
complex_array=np.array([1+2j,3+4j,5+6j])
print(complex_array)

[1.+2.j 3.+4.j 5.+6.j]


Q19.

In [94]:
import numpy as np
str_array=np.array(["1","2","3"])
int_array=str_array.astype(int)
print(int_array)

[1 2 3]


Q20.

In [95]:
import numpy as np
float_array=np.array([1.1,2.2,3.3,4.4,5.5])
int_array=float_array.astype(int)
print(int_array)

[1 2 3 4 5]
